version: "2.1"

services:
  postgres:
    container_name: postgres
    image: postgres:10
    environment:
      - "POSTGRES_USER=bugzilla"
      - "POSTGRES_PASSWORD=somepassword$$#!"
      - "POSTGRES_DB=bugzilla"
    networks:
      - bugzilla-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bugzilla"]
      interval: 15s
      timeout: 15s
      retries: 6
  bugzilla:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bugzilla-docker
    environment:
      - "DB_HOST=postgres"
      - "DB_USERNAME=bugzilla"
      - "DB_PASSWORD=somepassword$$#!"
    ports:
        - 80:80
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bugzilla-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 2s
      retries: 10

networks:
  bugzilla-network:
    name: bugzilla-network
    driver: bridge

